### ISSUE TITLE
Under Integration entries No devices or entities

### ISSUE THREAD

**Issue by brommetje** [nielsfaber/zoned-heating#15]
Hi All, 

Running HA 2023.10.3 and just installed Niels his integration, liked his idea zoned_heating very much and the winter is coming soon.

Under Integration entries No devices or entities visable, not after clearing browser cache or restart HA
![Integration entires](https://github.com/nielsfaber/zoned-heating/assets/41166144/bd03eebf-0b7a-41f1-be8b-e0b1cbd89433)
What I see is that one entity is created switch.zoned_heating
![developer tools entities](https://github.com/nielsfaber/zoned-heating/assets/41166144/7802cf93-d353-440f-8caf-971cf47fc563)

Is this a cosmetic issue, do I forget something, how can I solve this?

Martin

**Comment by stinobook** [comment]
This is how it works & is correct. 

when a TRV needs heat it will switch on the zoned heating switch and store the original value of  the controlling thermostat.

keep in mind you need a TRV in the same room as the thermostat and only control that room's temp via the TRV and no longer via the thermostat. 

the only thing this integration does is turn your thermostat into a switch to turn on your heating and use the TRV's as controllers for each individual room.

**Comment by brommetje** [comment]
Hi @stinobook if I understand it right, because I have a Toon1/thermostat (living room) that controls (controller) my boiler I still need a TRV in the living room, no radiators there. 

I only have one TRV in another room/zone at the moment.

 Then this solution is not working for me it looks like, correct if i’m wrong.

**Comment by stinobook** [comment]
Do you have in floor heating in the living room?
if so then indeed this integration won't work (or anything really..)
to use TRV's you need to be able close each individual room you want to heat separately. 

imagine it like this:
living room (no radiator trv) = 20
TRV room = 16.
you set TRV to 20 -> this integration (or any TRV setup) will check the controller temp (20) and add the difference (20-16).
living room gets set to 24. when TRV room is 20 it will return living room to previous state (20).

Now if you cannot close off the living room radiators this means each time you want to heat a TRV room ,your living room will also continue to warm up. 

If you have TRVs everywhere this idea works:
control: 20
liv TRV: 20
other TRV: 16
switch other to 20 -> control gets set to 24 but living TRV will close the circuit so the living room doens't get hotter yet since you're asking the controller to heat it to 24 (which it will never reach) it will start warming up the other room. once the room is at requested temp it sets control back to 20 and all is well.

**Comment by stinobook** [comment]
if you have in floor heating you could look up a way to add TRV's to the in floor heating circuit and so you can start using TRV's again. but its a little bit more complicated :) 
we have 2 circuits, radiator circuit and in floor heating circuit. one thermostat (controller) for in floor and one for radiator circuit. i have TRV's on all radiators. if you only have 1 controller its more complicated but also feasible.

**Comment by brommetje** [comment]
Thanks @stinobook for explaining this, and yes I have the floor heating and controller (rooted toon1) in the livingroom.

But what I have is a zone klep/motor (stelmotor) in the circuit and possibility to shut off the hot water supply to the floor heating by a shelly for a while but never used it.

Maybe I can use this to fake/create 2 circuits somehow?

**Comment by stinobook** [comment]
Ah if you can shut it off then you can easily create an automation so you can use your TRV yes. 
I also have an automation running on the zoned heating to double check it deactivates correctly since i use an EMS-ESP boiler (buderus) and sometimes the packet to disable the boiler gets lost. so i made an automation that keeps trying to shut off the boiler once zoned heating 'stops' 

see my automation below.
What you could to is :
Simple version:
from state false to true (zoned heating tries to warm the TRV room)
close the living room circuit with shelly 
true to false
open living room circuit.

You could make it more advanced:
if living room target temp > living room current temp:
do nothing and let TRV also warm TRV room.
If living room target < current:
close shelly circuit.

this way if you try to heat a different room it doesn't necesarily close the living room circuit if it also needs heat.

for this advanced version you're gonna need fake switches/thermostat/templates with the zoned heating 'stored controller value'  since zoned heating will put the controller way higher than you originally requested. 

if you want me to take a look at this (it shouldn't be too hard) hit me up on discord @stinobook and we can have a look :)

```

alias: ZonedHeatingHC3fix
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.zoned_heating
    attribute: override_active
    from: true
    to: false
  - platform: state
    entity_id:
      - climate.thermostat_hc3
    attribute: temperature
    enabled: true
condition:
  - condition: state
    entity_id: switch.zoned_heating
    attribute: override_active
    state: false
action:
  - repeat:
      until:
        - condition: state
          entity_id: climate.thermostat_hc3
          attribute: temperature
          state: 15
      sequence:
        - service: climate.set_temperature
          data:
            temperature: 15
          target:
            entity_id: climate.thermostat_hc3
        - delay:
            hours: 0
            minutes: 0
            seconds: 10
            milliseconds: 0
    enabled: true
mode: single

```
